### ISSUE TITLE
Strange error 

### ISSUE THREAD

**Issue by crankyz** [POSTECH-CVLab/PyTorch-StudioGAN#71]
Hello, when running:
CUDA_VISIBLE_DEVICES=0 python src/main.py -t -e -c CONFIG_PATH
Get this error:
Traceback (most recent call last):
  File "src/main.py", line 18, in <module>
    from loader import prepare_train_eval
  File "/home/igorv/PyTorch-StudioGAN/src/loader.py", line 14, in <module>
    from torchlars import LARS
  File "/home/igorv/anaconda3/envs/studio/lib/python3.7/site-packages/torchlars/__init__.py", line 2, in <module>
    from torchlars.lars import LARS
  File "/home/igorv/anaconda3/envs/studio/lib/python3.7/site-packages/torchlars/lars.py", line 6, in <module>
    from torchlars._adaptive_lr import compute_adaptive_lr
ImportError: /home/igorv/anaconda3/envs/studio/lib/python3.7/site-packages/torchlars/_adaptive_lr.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv

Any guess?

**Comment by MINGUKKANG** [comment]
Hi, 

I've never seen this kind of error :(

In fact, StudioGAN does not use the LARS optimizer. 

I added it because there are people who would like to use it, but if you don't use LARS optimizer, just remove it.

Thank you.

Best,

**Comment by crankyz** [comment]
That helps, ty.
