### ISSUE TITLE
Can I train GANs with this repository on CIFAR-100?

### ISSUE THREAD

**Issue by LeavesLei** [POSTECH-CVLab/PyTorch-StudioGAN#77]
Thanks for the great GAN repo!
I want to generate some images on **CIFAR-100**, and how can I use the repo to achieve this?

**Comment by MINGUKKANG** [comment]
Hi :)

The first thing you have to do is modifying the src/data_utils/data_loader.py file to load CIFAR100 dataset.
You may easily modify the data_loader.py using PyTorch's internal module (from torchvision.datasets import CIFAR100).

Then, modify a configuration in src/configs/CIFAR10/**.json for your purpose and relocate it to src/configs/CIFAR100/**.json.

After that, you can train a GAN on CIFAR100 dataset using the command below:

```
CUDA_VISIBLE_DEVICES=0 python3 src/main.py -t -e -l -rm_API -c "src/configs/CIFAR100/**.json" -stat_otf --eval_type "valid"
```

Lastly, get generated images from the pre-trained generator using: 
```
CUDA_VISIBLE_DEIVCES=0 python3 src/main.py -e -iv -s -c "src/configs/CIFAR100/**.json" -stat-otf --eval_type "valid"
```

Thank you.

**Comment by LeavesLei** [comment]
Thanks for your fast and clear reply😄

**Comment by LeavesLei** [comment]
BTW, should I create or change the save_path, i.e., the path where the well-trained models are saved?

**Comment by LeavesLei** [comment]
Hi, @MINGUKKANG , sorry to bother you again. It raises a error when I train a GAN on CIFAR-100:
> 10% 157/1563 [00:50<07:31,  3.12it/s]Traceback (most recent call last):
  File "src/main.py", line 120, in <module>
    main()
  File "src/main.py", line 117, in main
    prepare_train_eval(rank, gpus_per_node, world_size, run_name, train_configs, model_configs, hdf5_path_train=hdf5_path_train)
  File "/content/drive/My Drive/memorization and generalization/generate_dataset/PyTorch-StudioGAN/src/loader.py", line 248, in prepare_train_eval
    step = worker.train(current_step=step, total_step=cfgs.total_step)
  File "/content/drive/My Drive/memorization and generalization/generate_dataset/PyTorch-StudioGAN/src/worker.py", line 467, in train
    is_best = self.evaluation(step_count, False, "N/A")
  File "/content/drive/My Drive/memorization and generalization/generate_dataset/PyTorch-StudioGAN/src/worker.py", line 573, in evaluation
    self.latent_op_step4eval, self.latent_op_alpha, self.latent_op_beta, self.local_rank, self.logger)
  File "/content/drive/My Drive/memorization and generalization/generate_dataset/PyTorch-StudioGAN/src/metrics/F_beta.py", line 156, in calculate_f_beta_score
    prior, latent_op, latent_op_step, latent_op_alpha, latent_op_beta, batch_size, device)
  File "/content/drive/My Drive/memorization and generalization/generate_dataset/PyTorch-StudioGAN/src/metrics/F_beta.py", line 113, in compute_precision_recall
    real_images, real_labels = next(dataset_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1176, in _next_data
    raise StopIteration
StopIteration
 10% 157/1563 [00:51<07:42,  3.04it/s]

Besides, which type of scores (IS, FID, F_1/8, ...) do you rely on for identifying the best model during the training period? Hence, I can skip computing other scores for saving time.

**Comment by MINGUKKANG** [comment]
StudioGAN will automatically create a checkpoint folder (./checkpoints/RUN_NAME) and save a pre-trained model inside of it. 

Also,  there is a minor modification:
from
```
CUDA_VISIBLE_DEIVCES=0 python3 src/main.py -e -iv -s -c "src/configs/CIFAR100/**.json" -stat-otf --eval_type "valid"
```
to
```
CUDA_VISIBLE_DEIVCES=0 python3 src/main.py -e -iv -s -c "src/configs/CIFAR100/**.json" -stat-otf --eval_type "valid" --checkpoint_folder "./checkpoints/RUN_NAME"
```

Thank you.

**Comment by MINGUKKANG** [comment]
> Besides, which type of scores (IS, FID, F_1/8, ...) do you rely on for identifying the best model during the training period? Hence, I can skip computing other scores for saving time.
==> FID.

Also, please revise the dictionary below:

        if self.dataset_name == "imagenet":
            self.num_eval = {'train':50000, 'valid':50000}
        elif self.dataset_name == "tiny_imagenet":
            self.num_eval = {'train':50000, 'valid':10000}
        elif self.dataset_name == "cifar10":
            self.num_eval = {'train':50000, 'test':10000}
        else:
            num_train_images, num_eval_images = len(self.train_dataset.data), len(self.eval_dataset.data)
            self.num_eval = {'train':num_train_images, 'valid':num_eval_images} 
            
You should modify the lines above to suit your training configuration!
